import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google"
import Navigation from "@/components/nav";
import { LenisProvider } from "@/context/LenisScroll";

export const metadata: Metadata = {
  title: "Var",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  display: "swap",
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png"/>
      </head>
      <body
        className={`font-dm-sans antialiased ${dmSans.className}`}
      >
        <nav className="px-[5rem]">
          <Navigation />
        </nav>
        <main>
          <LenisProvider>
            {children}
          </LenisProvider>
        </main>
        <footer>

        </footer>
      </body>
    </html>
  );
}
